### ISSUE TITLE
Switch order of error and result parameters

### ISSUE THREAD

**Issue by curiousdannii** [jeromeetienne/gowiththeflow.js#7]
In my code at least, results are far more common than errors.

**Comment by jeromeetienne** [comment]
I dont understand please rephrase lots more details

**Comment by curiousdannii** [comment]
It seems nicer to me to have callback signatures of callback(next, result, error), and next(result, error). I haven't yet passed errors to the callback, but I do pass results. What reason did you have to pass errors first?

**Comment by jeromeetienne** [comment]
My intention was to copy step api . A lib from substack. But to make it works on browser too.

What is the default in node api? Can you provide links
